package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsInfo<M extends BaseNewsInfo<M>> extends Model<M> implements IBean {

	public void setAutoId(java.lang.Integer autoId) {
		set("auto_id", autoId);
	}
	
	public java.lang.Integer getAutoId() {
		return getInt("auto_id");
	}
	
	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	/**
	 * 正文
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 正文
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 发布单位
	 */
	public void setPubunit(java.lang.String pubunit) {
		set("pubunit", pubunit);
	}
	
	/**
	 * 发布单位
	 */
	public java.lang.String getPubunit() {
		return getStr("pubunit");
	}
	
	/**
	 * 发布时间
	 */
	public void setPubtime(java.util.Date pubtime) {
		set("pubtime", pubtime);
	}
	
	/**
	 * 发布时间
	 */
	public java.util.Date getPubtime() {
		return get("pubtime");
	}
	
}
