package com.demo.common.model;

import com.demo.common.model.base.BaseNewsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NewsInfo extends BaseNewsInfo<NewsInfo> {
	
}
